export { default as SEO } from './Seo/Seo';
export { default as Logo } from './Logo/Logo';
export { default as NavBar } from './Navbar/Navbar';
export { default as Layout } from './Layout/Layout';
export { default as Footer } from './Footer/Footer';
export { default as TatooImages } from './Images/TattooImages';
export { default as HaircutImages } from './Images/HaircutImages';
export { default as IntroContainer } from './IntroContainer/IntroContainer';
export { default as AboutMeSection } from './AboutMeSection/AboutMeSection';
